### ISSUE TITLE
Configuration key errors

### ISSUE THREAD

**Issue by andrewrynhard** [bhcleek/packer-provisioner-ansible#6]
Got the following error:
````
1 error(s) occurred:

* ssh_authorized_key_file must be specified.
````
Then after adding the required configuration keys:
````
3 error(s) occurred:

* Unknown configuration key: extra_arguments
* Unknown configuration key: ssh_authorized_key_file
* Unknown configuration key: ssh_host_key_file
````

**Comment by bhcleek** [comment]
Can you post the provisioner configuration causing these errors?

**Comment by bhcleek** [comment]
Closing for lack of details. Please submit a new issue if you're still encountering this and can provide the details needed to analyze further.

**Comment by foklepoint** [comment]
extra_arguments is not being recognized as a config option for me in 0.8.6 for the puppet-headless provisioner
