### ISSUE TITLE
Defining windows winrm

### ISSUE THREAD

**Issue by benashton2** [bhcleek/packer-provisioner-ansible#7]
Hi

How do you define the winrm connection stuff? I've tried below to no avail

    "provisioners": [
      {
        "type": "ansible",
        "playbook_file": "./playbook.yml",
        "ansible_ssh_user": "Administrator",
        "ansible_ssh_pass": "pass",
        "ansible_ssh_port": "5985",
        "ansible_connection": "winrm"
      }
    ]

Thanks

**Comment by bhcleek** [comment]
The provisioner uses SSH, not WinRM. If you're trying to provision a Windows node, then use an SSH connection from Ansible, and the WinRM communicator for the Packer builder: https://www.packer.io/docs/templates/communicator.html.

This provisioner is an adapter over the communication between Packer and the node that allows Ansible to communicate via SSH, without regard for how Packer communicates with the node.

**Comment by benashton2** [comment]
So the standard winrm configuration stuff already present in a Windows build should be sufficient?

**Comment by benashton2** [comment]
So I've tried doing the below and am getting a "failed to load authorized key file" error


{

    "provisioners": [
      {
        "type": "ansible",
        "playbook_file": "./playbook.yml",
        "ssh_host_key_file": "KEY.pem",
        "ssh_authorized_key_file": "KEY.pem"
      }
    ],

    "builders": [
      {
        "type": "amazon-ebs",
        "temporary_key_pair_name": "packer-temp",
        "security_group_id": "GROUP",
        "region": "eu-west-1",
        "source_ami": "ami-AMI",
        "instance_type": "t2.micro",
        "ami_name": "AMI",
        "subnet_id": "subnet-SUB",
        "ssh_keypair_name": "KEY",
        "associate_public_ip_address": true,
        "user_data_file": "scripts/setup_winrm.txt",
        "communicator": "winrm",
        "winrm_username": "Administrator",
        "winrm_password": "PASS",
        "winrm_port": "5985",
        "tags": {
          "Name": "NAME",
          "Environment": "Development",
          "Project": "PROJECT",
          "Owner": "OWNER",
          "Requestor": "OWNER",
          "Application": "APP",
          "Role": "ROLE",
          "CostCentre": "COST",
          "CreatedDate": "{{timestamp}}"
        }
      }
    ]

}

**Comment by bhcleek** [comment]
The provisioner configuration you have above looks correct, and the builder configuration looks right, too. I suspect you may be using an older version of packer that doesn't support the `communicator` configuration value. 

I'd recommend using the windows-shell provisioner first to make sure that you get communcation between packer and the node working correctly. After you've done that, you can focus on getting the ansible provisioner working.

**Comment by benashton2** [comment]
Hi, sorry for the late response.

It seems to be connecting with winrm and I have got other communicators working, I don't really understand the flow, in the error message it says "Connected to WinRM!" and then tries something with 127.0.0.1 - does it not run Ansible over the wirm connection? Extended error below.

==> amazon-ebs: Waiting for instance (ID) to become ready...
==> amazon-ebs: Skipping waiting for password since WinRM password set...
==> amazon-ebs: Waiting for WinRM to become available...
==> amazon-ebs: Connected to WinRM!
==> amazon-ebs: Provisioning with Ansible...
==> amazon-ebs: listen tcp 127.0.0.1:22: bind: permission denied
==> amazon-ebs: listen tcp 127.0.0.1:23: bind: permission denied
==> amazon-ebs: listen tcp 127.0.0.1:24: bind: permission denied

**Comment by bhcleek** [comment]
It does not run Ansible with the winrm connection. It starts up an SSH server, and configures the inventory file to connect to that SSH server on localhost.

**Comment by Qilinee** [comment]
I've decided to see if i can give this a shot myself but to no avail, very different results to the above though:

```
==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 5985 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-ad8aea2f
==> amazon-ebs: Waiting for instance (i-ad8aea2f) to become ready...
==> amazon-ebs: Skipping waiting for password since WinRM password set...
==> amazon-ebs: Waiting for WinRM to become available...
==> amazon-ebs: Connected to WinRM!
==> amazon-ebs: Provisioning with Ansible...
==> amazon-ebs: Executing Ansible: ansible-playbook /home/ubuntu/github/QilinAWS/packer/playbooks/windows/setup_iis.yml -i /tmp/packer-provisioner-ansible675659375 -vvvv
==> amazon-ebs: SSH proxy: serving on 127.0.0.1:58172
    amazon-ebs: Using /etc/ansible/ansible.cfg as config file
    amazon-ebs: Loaded callback default of type stdout, v2.0
    amazon-ebs: 1 plays in /home/ubuntu/github/QilinAWS/packer/playbooks/windows/setup_iis.yml
    amazon-ebs:
    amazon-ebs: PLAY [Install IIS and Download Site] *******************************************
    amazon-ebs:
    amazon-ebs: TASK [Install IIS] *************************************************************
    amazon-ebs: task path: /home/ubuntu/github/QilinAWS/packer/playbooks/windows/setup_iis.yml:8
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    amazon-ebs: <127.0.0.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=58172 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1459410075.99-265453842905384 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1459410075.99-265453842905384 `" )'"'"''
    amazon-ebs: SSH proxy: accepted connection
The authenticity of host '[127.0.0.1]:58172 ([127.0.0.1]:58172)' can't be established.
RSA key fingerprint is xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx.
Are you sure you want to continue connecting (yes/no)? yes
```

It wont move from that for a very, very long time. When i halt it the trace is

```
^C    amazon-ebs: Process WorkerProcess-2:
==> amazon-ebs: failed to handshake
    amazon-ebs: Traceback (most recent call last):
    amazon-ebs:   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    amazon-ebs:     self.run()
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/executor/process/worker.py", line 115, in run
    amazon-ebs:     self._shared_loader_obj,
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 120, in run
    amazon-ebs:     res = self._execute()
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 418, in _execute
    amazon-ebs:     result = self._handler.run(task_vars=variables)
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/plugins/action/normal.py", line 33, in run
    amazon-ebs:     results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/plugins/action/__init__.py", line 404, in _execute_module
    amazon-ebs:     tmp = self._make_tmp_path()
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/plugins/action/__init__.py", line 211, in _make_tmp_path
    amazon-ebs:     result = self._low_level_execute_command(cmd, sudoable=False)
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/plugins/action/__init__.py", line 520, in _low_level_execute_command
    amazon-ebs:     rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/plugins/connection/ssh.py", line 600, in exec_command
    amazon-ebs:     return_tuple = self._exec_command(*args, **kwargs)
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/plugins/connection/ssh.py", line 577, in _exec_command
    amazon-ebs:     (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
    amazon-ebs:   File "/usr/lib/pymodules/python2.7/ansible/plugins/connection/ssh.py", line 417, in _run
    amazon-ebs:     rfd, wfd, efd = select.select(rpipes, [], [], timeout)
    amazon-ebs: KeyboardInterrupt
    amazon-ebs:  [ERROR]: User interrupted execution
==> amazon-ebs: shutting down the SSH proxy
==> amazon-ebs: Terminating the source AWS instance...

```

My config is:
```

{

  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "playbooks/windows/setup_iis.yml",
      "ssh_host_key_file": "keypair-aws.pem",
      "ssh_authorized_key_file": "authorized_keys",
      "extra_arguments": "-vvvv"
    }
  ],
"builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "ap-southeast-2",
    "source_ami": "ami-1af6d779",
    "instance_type": "t2.micro",
    "communicator": "winrm",
    "winrm_username": "username",
    "winrm_password": "password",
    "winrm_port": "5985",
    "user_data_file": "userdata/packer_setup_winrm.txt",
    "ssh_keypair_name": "keypair-aws",
    "ssh_private_key_file": "keys/keypair-aws.pem",
    "ami_name": "{{timestamp}}"
  }]
}
```

Playbook is nothing fancy:
```
- name: Install IIS and Download Site
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        include_sub_features: yes
        include_management_tools: yes

```



I'm going to assume this is Ansible provisioner getting its signal sent over SSH to the Windows machine fine but it isn't finding something on Windows to run against and failing?
